version: 2
updates:
  - package-ecosystem: "npm"  # Using yarn for dependency management
    directory: "/client"
    allow:
      - dependency-type: 'direct'
    open-pull-requests-limit: 20
    schedule:
      interval: "weekly"
    versioning-strategy: "increase"
    target-branch: "develop"
    commit-message:
      prefix: "chore"  # Updated to "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "automerge"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "npm"  # Using yarn for dependency management
    directory: "/server"
    allow:
      - dependency-type: 'direct'
    open-pull-requests-limit: 20
    schedule:
      interval: "weekly"
    versioning-strategy: "increase"
    target-branch: "develop"
    commit-message:
      prefix: "chore"  # Updated to "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "automerge"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
