name: Release

on:
  workflow_run:
    workflows: ["frontend CI", "Server CI"]
    types:
      - completed
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    strategy:
      matrix:
        node-version: [18.x]

    name: Create a new release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Cache Yarn dependencies
        uses: actions/cache@v2.1.6
        with:
          path: ./node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('./client/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: install yarn
        run: npm install --global yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release